# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('pedidos', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('articulo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=5)),
                ('logo', models.FilePathField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('codigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='foto/')),
                ('descripcion', models.TextField(max_length=2000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('public_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('idC', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
